"""
Fear Less Maths -- 5-Month Personalised Class Plan (2026-27)
One entry per class: which FLM levels, which sublevels, and how many
sheets per sublevel, matching the published 5-month plan exactly
(16 FLM days/month x 5 months, 136-worksheet budget per student).
Used by class_plan_export.py to generate each class personalised ZIP.
"""

CLASS_PLAN_2026_27 = {'Class 1': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['1A', '1B', '1C', '1D', '1E', '1F', '1G', '1H', '1REV'],
              'level': 1,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A',
                                 'B',
                                 'C',
                                 'D',
                                 'E',
                                 'F',
                                 'G',
                                 'H',
                                 'I',
                                 'J',
                                 'K',
                                 'L',
                                 'M',
                                 'N',
                                 'O',
                                 'REV'],
              'level': 21,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'REV'],
              'level': 22,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 10': [{'high_sheets': ['1', '2', '3', '4'],
               'high_sublevels': ['12A', '12B', '12C', '12G', '12I', '12REV'],
               'level': 12,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['14A', '14B', '14C', '14D', '14E', '14F', '14G', '14REV'],
               'level': 14,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['16A', '16B', '16C', '16D', '16E', '16F', '16REV'],
               'level': 16,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['17A', '17B', '17C', '17D', '17E', '17F', '17REV'],
               'level': 17,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['19A', '19B', '19C', '19D', '19E', '19G', '19H', '19REV'],
               'level': 19,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['20A', '20B', '20D', '20E', '20F', '20G', '20H', '20I', '20REV'],
               'level': 20,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['15A', '15B', '15C', '15D', '15E', '15F', '15REV'],
               'level': 15,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['18A',
                                  '18B',
                                  '18C',
                                  '18D',
                                  '18E',
                                  '18F',
                                  '18G',
                                  '18H',
                                  '18I',
                                  '18REV'],
               'level': 18,
               'med_sheets': ['2', '3'],
               'med_sublevels': []}],
 'Class 2': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['1A', '1B', '1C', '1D', '1E', '1F', '1G', '1H', '1REV'],
              'level': 1,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['2A', '2B', '2C', '2D', '2E', '2F', '2G', '2H', '2I', '2REV'],
              'level': 2,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['3A',
                                 '3B',
                                 '3C',
                                 '3D',
                                 '3E',
                                 '3F',
                                 '3G',
                                 '3H',
                                 '3I',
                                 '3J',
                                 '3K',
                                 '3M',
                                 '3N',
                                 '3REV'],
              'level': 3,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['3L']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'REV'],
              'level': 23,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 3': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['3A',
                                 '3B',
                                 '3C',
                                 '3D',
                                 '3E',
                                 '3F',
                                 '3G',
                                 '3H',
                                 '3I',
                                 '3J',
                                 '3K',
                                 '3M',
                                 '3N',
                                 '3REV'],
              'level': 3,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['3L']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['4A',
                                 '4B',
                                 '4C',
                                 '4D',
                                 '4E',
                                 '4F',
                                 '4G',
                                 '4H',
                                 '4I',
                                 '4J',
                                 '4M',
                                 '4REV'],
              'level': 4,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'G', 'REV'],
              'level': 24,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['F']}],
 'Class 4': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['4A',
                                 '4B',
                                 '4C',
                                 '4D',
                                 '4E',
                                 '4F',
                                 '4G',
                                 '4H',
                                 '4I',
                                 '4J',
                                 '4M',
                                 '4REV'],
              'level': 4,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['4K', '4L']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['5A',
                                 '5B',
                                 '5C',
                                 '5D',
                                 '5E',
                                 '5F',
                                 '5G',
                                 '5H',
                                 '5I',
                                 '5L',
                                 '5M',
                                 '5REV'],
              'level': 5,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['5J', '5K']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['6A',
                                 '6B',
                                 '6C',
                                 '6D',
                                 '6E',
                                 '6F',
                                 '6G',
                                 '6H',
                                 '6I',
                                 '6J',
                                 '6K',
                                 '6L',
                                 '6N',
                                 '6REV'],
              'level': 6,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['6M']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A',
                                 '18B',
                                 '18C',
                                 '18D',
                                 '18E',
                                 '18F',
                                 '18G',
                                 '18H',
                                 '18I',
                                 '18REV'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 5': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['5A',
                                 '5B',
                                 '5C',
                                 '5D',
                                 '5E',
                                 '5F',
                                 '5G',
                                 '5H',
                                 '5I',
                                 '5L',
                                 '5M',
                                 '5REV'],
              'level': 5,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['5J', '5K']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['6A',
                                 '6B',
                                 '6C',
                                 '6D',
                                 '6E',
                                 '6F',
                                 '6G',
                                 '6H',
                                 '6I',
                                 '6J',
                                 '6K',
                                 '6L',
                                 '6N',
                                 '6REV'],
              'level': 6,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['6M']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['7A',
                                 '7B',
                                 '7C',
                                 '7D',
                                 '7E',
                                 '7F',
                                 '7G',
                                 '7H',
                                 '7I',
                                 '7J',
                                 '7K',
                                 '7M',
                                 '7REV'],
              'level': 7,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['7L']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A',
                                 '18B',
                                 '18C',
                                 '18D',
                                 '18E',
                                 '18F',
                                 '18G',
                                 '18H',
                                 '18I',
                                 '18REV'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 6': [{'high_sheets': ['2', '3'],
              'high_sublevels': ['6A',
                                 '6B',
                                 '6C',
                                 '6D',
                                 '6E',
                                 '6F',
                                 '6G',
                                 '6H',
                                 '6I',
                                 '6J',
                                 '6K',
                                 '6L',
                                 '6N',
                                 '6REV'],
              'level': 6,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['6M']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['7A',
                                 '7B',
                                 '7C',
                                 '7D',
                                 '7E',
                                 '7F',
                                 '7G',
                                 '7H',
                                 '7I',
                                 '7J',
                                 '7K',
                                 '7M',
                                 '7REV'],
              'level': 7,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['8A', '8B', '8C', '8D', '8E', '8F', '8H', '8REV'],
              'level': 8,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['9A', '9B', '9C', '9D', '9E', '9REV'],
              'level': 9,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['10A', '10B', '10C', '10D', '10E', '10G', '10H', '10REV'],
              'level': 10,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['11A', '11B', '11C', '11D', '11E', '11F', '11H', '11REV'],
              'level': 11,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A',
                                 '18B',
                                 '18C',
                                 '18D',
                                 '18E',
                                 '18F',
                                 '18G',
                                 '18H',
                                 '18I',
                                 '18REV'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 7': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['8A', '8B', '8C', '8D', '8E', '8F', '8H', '8REV'],
              'level': 8,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['9A', '9B', '9C', '9D', '9E', '9REV'],
              'level': 9,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['11A', '11B', '11C', '11D', '11E', '11F', '11H', '11REV'],
              'level': 11,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['12A', '12B', '12C', '12G', '12I', '12REV'],
              'level': 12,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['10A', '10B', '10C', '10D', '10E', '10G', '10H', '10REV'],
              'level': 10,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['13A', '13B', '13C', '13D', '13E', '13F', '13REV'],
              'level': 13,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['16A', '16B', '16C', '16D', '16E', '16F', '16REV'],
              'level': 16,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A',
                                 '18B',
                                 '18C',
                                 '18D',
                                 '18E',
                                 '18F',
                                 '18G',
                                 '18H',
                                 '18I',
                                 '18REV'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 8': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['11A', '11B', '11C', '11D', '11E', '11F', '11H', '11REV'],
              'level': 11,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['12A', '12B', '12C', '12G', '12I', '12REV'],
              'level': 12,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['10A', '10B', '10C', '10D', '10E', '10G', '10H', '10REV'],
              'level': 10,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['13A', '13B', '13C', '13D', '13E', '13F', '13REV'],
              'level': 13,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['14A', '14B', '14C', '14D', '14E', '14F', '14G', '14REV'],
              'level': 14,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['15A', '15B', '15C', '15D', '15E', '15F', '15REV'],
              'level': 15,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A',
                                 '18B',
                                 '18C',
                                 '18D',
                                 '18E',
                                 '18F',
                                 '18G',
                                 '18H',
                                 '18I',
                                 '18REV'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 9': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['12A', '12B', '12C', '12G', '12I', '12REV'],
              'level': 12,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['14A', '14B', '14C', '14D', '14E', '14F', '14G', '14REV'],
              'level': 14,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['16A', '16B', '16C', '16D', '16E', '16F', '16REV'],
              'level': 16,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['16G']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['17A', '17B', '17C', '17D', '17E', '17F', '17REV'],
              'level': 17,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['20A', '20B', '20D', '20E', '20F', '20G', '20H', '20I', '20REV'],
              'level': 20,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['13A', '13B', '13C', '13D', '13E', '13F', '13REV'],
              'level': 13,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['15A', '15B', '15C', '15D', '15E', '15F', '15REV'],
              'level': 15,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A',
                                 '18B',
                                 '18C',
                                 '18D',
                                 '18E',
                                 '18F',
                                 '18G',
                                 '18H',
                                 '18I',
                                 '18REV'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'LKG': [{'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'REV'],
          'level': 0,
          'med_sheets': ['2', '3'],
          'med_sublevels': []},
         {'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A',
                             'B',
                             'C',
                             'D',
                             'E',
                             'F',
                             'G',
                             'H',
                             'I',
                             'J',
                             'K',
                             'L',
                             'M',
                             'N',
                             'O',
                             'REV'],
          'level': 21,
          'med_sheets': ['2', '3'],
          'med_sublevels': []}],
 'Nursery': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'REV'],
              'level': 0,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'UKG': [{'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A',
                             'B',
                             'C',
                             'D',
                             'E',
                             'F',
                             'G',
                             'H',
                             'I',
                             'J',
                             'K',
                             'L',
                             'M',
                             'N',
                             'O',
                             'REV'],
          'level': 21,
          'med_sheets': ['2', '3'],
          'med_sublevels': []},
         {'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'REV'],
          'level': 22,
          'med_sheets': ['2', '3'],
          'med_sublevels': []}]}
