"""
Fear Less Maths -- 5-Month Personalised Class Plan (2026-27)
One entry per class: which FLM levels, which sublevels, and how many
sheets per sublevel, matching the published 5-month plan (16 FLM
days/month x 5 months, 136-worksheet budget per student).
Used by class_plan_export.py to generate each class personalised ZIP.

v2 fixes (see conversation history): REV sublevels (e.g. "9REV") were
being wrongly counted as core HIGH content because their topic text
("Level 9 Revision") did not literally start with the word "review" --
fixed by also checking for "REV" in the sublevel CODE. Level 9
(Factors/Multiples/HCF/LCM) was also missing entirely from Classes
8, 9, and 10 -- added back as a carried-forward maintained skill.
"""

CLASS_PLAN_2026_27 = {'Class 1': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['1A', '1B', '1C', '1D', '1E', '1F', '1G', '1H'],
              'level': 1,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A',
                                 'B',
                                 'C',
                                 'D',
                                 'E',
                                 'F',
                                 'G',
                                 'H',
                                 'I',
                                 'J',
                                 'K',
                                 'L',
                                 'M',
                                 'N',
                                 'O'],
              'level': 21,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
              'level': 22,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 10': [{'high_sheets': ['1', '2', '3', '4'],
               'high_sublevels': ['12A', '12B', '12C', '12G', '12I'],
               'level': 12,
               'med_sheets': ['2', '3'],
               'med_sublevels': ['12D', '12E']},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['14A', '14B', '14C', '14D', '14E', '14F', '14G'],
               'level': 14,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['16A', '16B', '16C', '16D', '16E', '16F'],
               'level': 16,
               'med_sheets': ['2', '3'],
               'med_sublevels': ['16G']},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['17A', '17B', '17C', '17D', '17E', '17F'],
               'level': 17,
               'med_sheets': ['2', '3'],
               'med_sublevels': ['17G']},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['19A', '19B', '19C', '19D', '19E', '19G', '19H'],
               'level': 19,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['20A', '20B', '20D', '20E', '20F', '20G', '20H', '20I'],
               'level': 20,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['15A', '15B', '15C', '15D', '15E', '15F'],
               'level': 15,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['9A', '9B', '9C', '9D', '9E'],
               'level': 9,
               'med_sheets': ['2', '3'],
               'med_sublevels': []},
              {'high_sheets': ['2', '3'],
               'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
               'level': 18,
               'med_sheets': ['2', '3'],
               'med_sublevels': []}],
 'Class 2': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['1A', '1B', '1C', '1D', '1E', '1F', '1G', '1H'],
              'level': 1,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['2A', '2B', '2C', '2D', '2E', '2F', '2G', '2H', '2I'],
              'level': 2,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['3A',
                                 '3B',
                                 '3C',
                                 '3D',
                                 '3E',
                                 '3F',
                                 '3G',
                                 '3H',
                                 '3I',
                                 '3J',
                                 '3K',
                                 '3M',
                                 '3N'],
              'level': 3,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['3L']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F'],
              'level': 23,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 3': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['3A',
                                 '3B',
                                 '3C',
                                 '3D',
                                 '3E',
                                 '3F',
                                 '3G',
                                 '3H',
                                 '3I',
                                 '3J',
                                 '3K',
                                 '3M',
                                 '3N'],
              'level': 3,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['3L']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['4A', '4B', '4C', '4D', '4E', '4F', '4G', '4H', '4I', '4J', '4M'],
              'level': 4,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['4K', '4L']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'G'],
              'level': 24,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['F']}],
 'Class 4': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['4A', '4B', '4C', '4D', '4E', '4F', '4G', '4H', '4I', '4J', '4M'],
              'level': 4,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['4K', '4L']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['5A', '5B', '5C', '5D', '5E', '5F', '5G', '5H', '5I', '5L', '5M'],
              'level': 5,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['6A',
                                 '6B',
                                 '6C',
                                 '6D',
                                 '6E',
                                 '6F',
                                 '6G',
                                 '6H',
                                 '6I',
                                 '6J',
                                 '6K',
                                 '6L',
                                 '6N'],
              'level': 6,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 5': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['5A', '5B', '5C', '5D', '5E', '5F', '5G', '5H', '5I', '5L', '5M'],
              'level': 5,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['6A',
                                 '6B',
                                 '6C',
                                 '6D',
                                 '6E',
                                 '6F',
                                 '6G',
                                 '6H',
                                 '6I',
                                 '6J',
                                 '6K',
                                 '6L',
                                 '6N'],
              'level': 6,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['7A',
                                 '7B',
                                 '7C',
                                 '7D',
                                 '7E',
                                 '7F',
                                 '7G',
                                 '7H',
                                 '7I',
                                 '7J',
                                 '7K',
                                 '7M'],
              'level': 7,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 6': [{'high_sheets': ['2', '3'],
              'high_sublevels': ['6A',
                                 '6B',
                                 '6C',
                                 '6D',
                                 '6E',
                                 '6F',
                                 '6G',
                                 '6H',
                                 '6I',
                                 '6J',
                                 '6K',
                                 '6L',
                                 '6N'],
              'level': 6,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['6M']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['7A',
                                 '7B',
                                 '7C',
                                 '7D',
                                 '7E',
                                 '7F',
                                 '7G',
                                 '7H',
                                 '7I',
                                 '7J',
                                 '7K',
                                 '7M'],
              'level': 7,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['8A', '8B', '8C', '8D', '8E', '8F', '8H'],
              'level': 8,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['9A', '9B', '9C', '9D', '9E'],
              'level': 9,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['10A', '10B', '10C', '10D', '10E', '10G', '10H'],
              'level': 10,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['11A', '11B', '11C', '11D', '11E', '11F', '11H'],
              'level': 11,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 7': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['8A', '8B', '8C', '8D', '8E', '8F', '8H'],
              'level': 8,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['8G']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['9A', '9B', '9C', '9D', '9E'],
              'level': 9,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['9F', '9G']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['11A', '11B', '11C', '11D', '11E', '11F', '11H'],
              'level': 11,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['11G']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['12A', '12B', '12C', '12G', '12I'],
              'level': 12,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['10A', '10B', '10C', '10D', '10E', '10G', '10H'],
              'level': 10,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['13A', '13B', '13C', '13D', '13E', '13F'],
              'level': 13,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['16A', '16B', '16C', '16D', '16E', '16F'],
              'level': 16,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 8': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['11A', '11B', '11C', '11D', '11E', '11F', '11H'],
              'level': 11,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['11G']},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['12A', '12B', '12C', '12G', '12I'],
              'level': 12,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['12D', '12E']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['10A', '10B', '10C', '10D', '10E', '10G', '10H'],
              'level': 10,
              'med_sheets': ['2', '3'],
              'med_sublevels': ['10F']},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['13A', '13B', '13C', '13D', '13E', '13F'],
              'level': 13,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['14A', '14B', '14C', '14D', '14E', '14F', '14G'],
              'level': 14,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['15A', '15B', '15C', '15D', '15E', '15F'],
              'level': 15,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['9A', '9B', '9C', '9D', '9E'],
              'level': 9,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'Class 9': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['12A', '12B', '12C', '12G', '12I'],
              'level': 12,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['14A', '14B', '14C', '14D', '14E', '14F', '14G'],
              'level': 14,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['16A', '16B', '16C', '16D', '16E', '16F'],
              'level': 16,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['17A', '17B', '17C', '17D', '17E', '17F'],
              'level': 17,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['20A', '20B', '20D', '20E', '20F', '20G', '20H', '20I'],
              'level': 20,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['13A', '13B', '13C', '13D', '13E', '13F'],
              'level': 13,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['15A', '15B', '15C', '15D', '15E', '15F'],
              'level': 15,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['9A', '9B', '9C', '9D', '9E'],
              'level': 9,
              'med_sheets': ['2', '3'],
              'med_sublevels': []},
             {'high_sheets': ['2', '3'],
              'high_sublevels': ['18A', '18B', '18C', '18D', '18E', '18F', '18G', '18H', '18I'],
              'level': 18,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'LKG': [{'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
          'level': 0,
          'med_sheets': ['2', '3'],
          'med_sublevels': []},
         {'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A',
                             'B',
                             'C',
                             'D',
                             'E',
                             'F',
                             'G',
                             'H',
                             'I',
                             'J',
                             'K',
                             'L',
                             'M',
                             'N',
                             'O'],
          'level': 21,
          'med_sheets': ['2', '3'],
          'med_sublevels': []}],
 'Nursery': [{'high_sheets': ['1', '2', '3', '4'],
              'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
              'level': 0,
              'med_sheets': ['2', '3'],
              'med_sublevels': []}],
 'UKG': [{'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A',
                             'B',
                             'C',
                             'D',
                             'E',
                             'F',
                             'G',
                             'H',
                             'I',
                             'J',
                             'K',
                             'L',
                             'M',
                             'N',
                             'O'],
          'level': 21,
          'med_sheets': ['2', '3'],
          'med_sublevels': []},
         {'high_sheets': ['1', '2', '3', '4'],
          'high_sublevels': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
          'level': 22,
          'med_sheets': ['2', '3'],
          'med_sublevels': []}]}
