"""
Fear Less Maths — PRE-LEVEL Content (Pre-Primary / Class 1 entry)
Singapore-Math CPA approach: Concrete -> Pictorial -> Pictorial-Abstract bridge -> Abstract.
Every sub-level has exactly 4 sheets matching the existing Intro/Concept/Practice/Mastery
naming used everywhere else in the app, but the MEANING of each sheet is redefined here
to follow CPA stages (see table below). Remedial (R) variants are auto-generated by
remedialise() in content.py, extended to also shrink object counts in diagram params.

CPA <-> Sheet mapping used in every PreLevel sub-level:
  Sheet 1  Intro     = Concrete    : real objects, rows of <=5, plain counting
  Sheet 2  Concept   = Pictorial   : objects grouped in 5s/10s (subitizing) + concept box
  Sheet 3  Practice  = Bridge      : objects + number support (tips box, partial symbols)
  Sheet 4  Mastery   = Abstract    : numbers/symbols only, no images

Object kinds cycle through: apple, star, balloon, flower  (matches diagram_engine.py)
"""
import random
from content import cb, tb, q, remedialise  # reuse existing helpers

OBJ_KINDS = ["apple", "star", "balloon", "flower"]


def _kind(i):
    return OBJ_KINDS[i % len(OBJ_KINDS)]


def _count_q(n, kind, group_size=5):
    """One counting question: show n objects, ask the student to count & write."""
    return q("Count the objects and write the number.", "diagram",
              "Number = ____", "", "object_group",
              {"count": n, "kind": kind, "group_size": group_size})


def _compare_q(left, right, kind):
    return q("Look at both groups. Circle the group with MORE objects.", "diagram",
              "Bigger group = Left / Right", "", "object_compare",
              {"left_count": left, "right_count": right, "kind": kind})


def _draw_q(n):
    """Reverse-direction question: given a number, child draws that many objects.
    Printed worksheet leaves a blank box; no diagram needed."""
    return q(f"Draw {n} circles (●) in the box below.", "fill", "(draw in the box)")


def _one_more_q(n, kind):
    return q(f"Look at the {n} {kind}s. Draw ONE MORE and write the new total.",
             "diagram", "New total = ____", "", "object_group",
             {"count": n, "kind": kind, "group_size": 5})


def _one_less_q(n, kind):
    return q(f"Look at the {n} {kind}s. Cross out ONE and write what is left.",
             "diagram", "Now there are = ____", "", "object_group",
             {"count": n, "kind": kind, "group_size": 5})


def _gen_riddle(lo_start, hi_start, lo_change, hi_change, kind, op="more"):
    """Programmatically generate a simple addition/subtraction riddle to top up
    PreI sheets without hand-writing every single line."""
    start = random.randint(lo_start, hi_start)
    change = random.randint(lo_change, hi_change)
    if op == "more":
        ans = start + change
        verb = "come" if kind in ("balloon", "star") else "are added"
        text = f"There are {start} {kind}s. {change} more {verb}. How many now?"
    else:
        change = min(change, start - 1) if start > 1 else 1
        ans = start - change
        verb = "fly away" if kind in ("balloon", "star") else "are taken away"
        text = f"There are {start} {kind}s. {change} {verb}. How many are left?"
    return q(text, "word", f"Answer = ____ (Answer: {ans})")


# ───────────────────────── Counting blocks: PreA-PreD (1-20) ─────────────────────────

def _counting_block(lo, hi, sheet, label):
    """Builds one sheet (Intro/Concept/Practice/Mastery) for a counting range lo..hi."""
    random.seed(lo * 10 + sheet)
    span = list(range(lo, hi + 1))
    picks = [random.choice(span) for _ in range(19)]  # sample w/ replacement, enough for ~16 real Qs

    if sheet == 1:  # Concrete — plain object counting, single kind per question
        items = [cb(f"Counting {lo} to {hi}",
                     ["Touch each object and count one by one.",
                      "Say the number out loud as you touch it.",
                      "Count slowly — do not skip any object."],
                     f"Count: {lo}, {lo+1}, {lo+2}... up to {hi}")]
        for idx, n in enumerate(picks):
            items.append(_count_q(n, _kind(idx)))
        return items

    if sheet == 2:  # Pictorial — grouped in 5s, subitizing
        items = [cb("Counting in Groups of 5",
                     ["Objects are arranged in rows of 5.",
                      "Count one full row first — that is 5.",
                      "Then count the extra objects in the next row."],
                     "Row of 5 + 2 more = 7")]
        for idx, n in enumerate(picks):
            items.append(_count_q(n, _kind(idx), group_size=5))
        return items

    if sheet == 3:  # Bridge — tips box, mix of counting + reverse drawing
        items = [tb(f"Tips for Counting {lo}-{hi}",
                     ["Always start counting from 1, not from the last object.",
                      "Move your finger under each object as you count.",
                      "Check your answer by counting again."])]
        for idx, n in enumerate(picks[:12]):
            items.append(_count_q(n, _kind(idx)))
        for n in picks[12:19]:
            items.append(_draw_q(n))
        return items

    # sheet == 4: Abstract — numbers only, no images
    items = [cb(f"Numbers {lo} to {hi}",
                 ["We can also count using number words, without pictures.",
                  "Numbers go up by 1 each time.",
                  f"After {hi-1} comes {hi}."],
                 f"{hi-2}, {hi-1}, {hi}")]
    for n in picks[:10]:
        items.append(q(f"Write the number that comes just AFTER {n}.", "fill", "Answer = ____"))
    for n in picks[10:19]:
        items.append(q(f"Write the number that comes just BEFORE {n}.", "fill", "Answer = ____"))
    return items


def _A_s(sheet): return _counting_block(1, 5, sheet, "A")
def _B_s(sheet): return _counting_block(6, 10, sheet, "B")
def _C_s(sheet): return _counting_block(11, 15, sheet, "C")
def _D_s(sheet): return _counting_block(16, 20, sheet, "D")


# ───────────────────────── PreCUM1: cumulative review 1-20 ─────────────────────────

def _CUM1_s(sheet):
    random.seed(100 + sheet)
    counts = [random.choice(range(1, 21)) for _ in range(19)]
    if sheet == 1:
        items = [cb("Review: Counting 1 to 20",
                     ["This sheet mixes numbers from 1 to 20.",
                      "Count carefully — some groups are small, some are bigger."],
                     "Practice counting any group from 1 to 20")]
        items += [_count_q(n, _kind(i)) for i, n in enumerate(counts)]
        return items
    if sheet == 2:
        items = [cb("Review: Counting in Groups",
                     ["Look for full rows of 5 first.",
                      "Then add the leftover objects."],
                     "5 + 5 + 3 = 13")]
        items += [_count_q(n, _kind(i), group_size=5) for i, n in enumerate(counts)]
        return items
    if sheet == 3:
        items = [tb("Review Tips",
                     ["If you lose count, start over from 1.",
                      "Counting out loud helps you stay accurate."])]
        items += [_count_q(n, _kind(i)) for i, n in enumerate(counts[:11])]
        items += [_draw_q(n) for n in counts[11:19]]
        return items
    items = [cb("Numbers 1 to 20 — No Pictures",
                 ["You should now recognise numbers without counting objects.",
                  "Practice writing numbers in order."],
                 "1, 2, 3 ... 20")]
    for n in counts:
        items.append(q(f"What number comes right after {n}?", "fill", "Answer = ____"))
    return items


# ───────────────────────── PreE: Number-to-picture matching (reverse) ─────────────────────────

def _E_s(sheet):
    random.seed(200 + sheet)
    if sheet == 1:
        items = [cb("From Number to Picture",
                     ["This time you see a NUMBER first.",
                      "Draw that many objects in the box.",
                      "Count your drawing to check it matches the number."],
                     "Number 4 -> draw 4 circles")]
        for n in [random.choice(range(1, 6)) for _ in range(19)]:
            items.append(_draw_q(n))
        return items
    if sheet == 2:
        items = [cb("Matching Groups of 5 and 10",
                     ["If the number is more than 5, draw one row of 5 first.",
                      "Then draw the rest in a second row."],
                     "Number 8 -> row of 5 + row of 3")]
        for n in [random.choice(range(6, 11)) for _ in range(19)]:
            items.append(_draw_q(n))
        return items
    if sheet == 3:
        items = [tb("Drawing Tips",
                     ["Draw simple shapes like circles or stars — keep them small.",
                      "Leave a little space between each object so counting is easy."])]
        for n in [random.choice(range(1, 16)) for _ in range(19)]:
            items.append(_draw_q(n))
        return items
    items = [cb("Number Recognition", ["Match numbers without drawing — just identify them."],
                "Which is bigger, 12 or 15? -> 15")]
    for _ in range(19):
        a, b = random.sample(range(1, 21), 2)
        items.append(q(f"Which number is bigger: {a} or {b}?", "fill", "Bigger = ____"))
    return items


# ───────────────────────── PreF: One More ─────────────────────────

def _F_s(sheet):
    random.seed(300 + sheet)
    nums = [random.choice(range(1, 15)) for _ in range(19)]
    if sheet == 1:
        items = [cb("One More",
                     ["When we add ONE MORE, we move forward by 1.",
                      "Count the objects, then add 1 more and count again."],
                     "3 apples + 1 more = 4 apples")]
        items += [_one_more_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 2:
        items = [cb("One More — Using Groups",
                     ["Count the full row of 5 first, then the extra ones.",
                      "Adding one more only changes the last group."],
                     "Row of 5 + 2, one more makes Row of 5 + 3")]
        items += [_one_more_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 3:
        items = [tb("One More Tips",
                     ["'One more' always means add 1.",
                      "The new number is always 1 bigger than before."])]
        for n in nums:
            items.append(q(f"What is one more than {n}?", "fill", "Answer = ____"))
        return items
    items = [cb("One More — Numbers Only",
                 ["You no longer need pictures — just add 1 to the number."],
                 "One more than 9 is 10")]
    for n in [random.choice(range(1, 21)) for _ in range(19)]:
        items.append(q(f"One more than {n} is ____.", "fill", "Answer = ____"))
    return items


# ───────────────────────── PreG: One Less ─────────────────────────

def _G_s(sheet):
    random.seed(400 + sheet)
    nums = [random.choice(range(2, 16)) for _ in range(19)]
    if sheet == 1:
        items = [cb("One Less",
                     ["When we take away ONE, we move backward by 1.",
                      "Cross out one object, then count what is left."],
                     "5 stars, cross out 1 = 4 stars")]
        items += [_one_less_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 2:
        items = [cb("One Less — Using Groups",
                     ["If a full row of 5 has one removed, it becomes 4.",
                      "Count groups first, then subtract 1 from the total."],
                     "Row of 5, minus 1 = 4")]
        items += [_one_less_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 3:
        items = [tb("One Less Tips",
                     ["'One less' always means subtract 1.",
                      "The new number is always 1 smaller than before."])]
        for n in nums:
            items.append(q(f"What is one less than {n}?", "fill", "Answer = ____"))
        return items
    items = [cb("One Less — Numbers Only",
                 ["Subtract 1 from the number directly — no pictures needed."],
                 "One less than 10 is 9")]
    for n in [random.choice(range(2, 21)) for _ in range(19)]:
        items.append(q(f"One less than {n} is ____.", "fill", "Answer = ____"))
    return items


# ───────────────────────── PreCUM2: One more / one less combined ─────────────────────────

def _CUM2_s(sheet):
    random.seed(500 + sheet)
    nums = [random.choice(range(2, 19)) for _ in range(19)]
    if sheet == 1:
        items = [cb("Review: One More & One Less",
                     ["One more means +1. One less means -1.",
                      "Read each question carefully before answering."],
                     "One more than 6 = 7.  One less than 6 = 5.")]
        for i, n in enumerate(nums[:10]):
            items.append(_one_more_q(n, _kind(i)))
        for i, n in enumerate(nums[10:]):
            items.append(_one_less_q(n, _kind(i)))
        return items
    if sheet == 2:
        items = [cb("Review — Using Groups of 5", ["Use the rows of 5 to check your counting."],
                     "Group view helps avoid mistakes")]
        for i, n in enumerate(nums[:10]):
            items.append(_one_more_q(n, _kind(i)))
        for i, n in enumerate(nums[10:]):
            items.append(_one_less_q(n, _kind(i)))
        return items
    if sheet == 3:
        items = [tb("Review Tips", ["Look for the words 'more' or 'less' before answering.",
                                     "More = bigger number. Less = smaller number."])]
        for n in nums:
            items.append(q(f"Is 'one more than {n}' bigger or smaller than {n}?", "fill", "Answer = ____"))
        return items
    items = [cb("Numbers Only — One More / One Less",
                 ["Apply +1 or -1 directly to the number."], "")]
    for n in nums:
        items.append(q(f"One more than {n} = ____, one less than {n} = ____.", "fill", "Answers = ____ , ____"))
    return items


# ───────────────────────── PreH: Comparing groups (more/fewer) ─────────────────────────

def _H_s(sheet):
    random.seed(600 + sheet)
    pairs = [(random.randint(1, 8), random.randint(1, 8)) for _ in range(19)]
    if sheet == 1:
        items = [cb("More or Fewer",
                     ["Look at two groups of objects.",
                      "The group with MORE objects has a bigger number.",
                      "Compare by counting each group separately."],
                     "4 apples vs 6 apples -> 6 is more")]
        items += [_compare_q(l, r, _kind(i)) for i, (l, r) in enumerate(pairs)]
        return items
    if sheet == 2:
        items = [cb("Comparing Using Groups of 5",
                     ["Line up both groups in rows of 5 to compare faster.",
                      "Whichever group fills more rows is bigger."],
                     "")]
        items += [_compare_q(l, r, _kind(i)) for i, (l, r) in enumerate(pairs)]
        return items
    if sheet == 3:
        items = [tb("Comparing Tips",
                     ["Count both groups fully before deciding.",
                      "Do not guess by size of the picture — always count."])]
        for l, r in pairs:
            items.append(q(f"Which is bigger: {l} or {r}?", "fill", "Bigger = ____"))
        return items
    items = [cb("Comparing Numbers", ["Compare numbers directly without pictures."], "7 > 5")]
    for l, r in pairs:
        items.append(q(f"Fill in: {l} ___ {r}  (write > , < or =)", "fill", "Answer = ____"))
    return items


# ───────────────────────── PreI: Simple picture puzzles ─────────────────────────

def _I_s(sheet):
    random.seed(700 + sheet)
    if sheet == 1:
        items = [cb("Picture Riddles",
                     ["Read the riddle and picture it in your head.",
                      "Count using your fingers if needed."],
                     "I have 3 apples. I get 1 more. How many now? -> 4")]
        riddles = [
            ("I see 2 balloons. 2 more come. How many now?", 4),
            ("I have 5 stars. 1 flies away. How many are left?", 4),
            ("There are 3 flowers. I plant 2 more. How many now?", 5),
            ("I have 4 apples. I eat 1. How many are left?", 3),
            ("I see 1 balloon. 4 more come. How many now?", 5),
            ("I have 2 apples. I get 2 more. How many now?", 4),
            ("There are 4 stars. 1 falls. How many are left?", 3),
            ("I see 3 balloons. 1 more comes. How many now?", 4),
            ("There are 2 flowers. I pick 1. How many are left?", 1),
            ("I have 1 apple. I get 3 more. How many now?", 4),
            ("I see 5 stars. 2 fly away. How many are left?", 3),
            ("There are 1 balloon. 1 more comes. How many now?", 2),
        ]
        for text, ans in riddles:
            items.append(q(text, "word", f"Answer = ____ (Answer: {ans})"))
        for i in range(19 - len(riddles)):
            items.append(_gen_riddle(1, 5, 1, 4, _kind(i), "more" if i % 2 == 0 else "less"))
        return items
    if sheet == 2:
        items = [cb("Riddles with Groups",
                     ["Draw the objects in groups of 5 to solve faster."], "")]
        riddles = [
            ("There are 6 apples in a basket. 3 more are added. How many now?", 9),
            ("I have 8 stars. I give away 2. How many are left?", 6),
            ("7 balloons are tied. 2 burst. How many are left?", 5),
            ("There are 5 flowers. 5 more grow. How many now?", 10),
            ("9 apples on a tree. 4 fall down. How many are left?", 5),
            ("6 stars in the sky. 4 more appear. How many now?", 10),
            ("There are 10 balloons. 3 fly away. How many are left?", 7),
            ("8 flowers in a pot. 2 more are planted. How many now?", 10),
            ("There are 7 apples. 5 are eaten. How many are left?", 2),
            ("6 balloons, 6 more come. How many now?", 12),
            ("9 stars, 3 fall. How many are left?", 6),
        ]
        for text, ans in riddles:
            items.append(q(text, "word", f"Answer = ____ (Answer: {ans})"))
        for i in range(19 - len(riddles)):
            items.append(_gen_riddle(4, 9, 1, 5, _kind(i), "more" if i % 2 == 0 else "less"))
        return items
    if sheet == 3:
        items = [tb("Riddle-Solving Tips",
                     ["Underline the starting number and the change number.",
                      "Decide if the riddle means 'more' (add) or 'less' (subtract)."])]
        riddles = [
            ("I had 10 stars, I lost 3. How many now?", 7),
            ("I had 6 apples, I got 6 more. How many now?", 12),
            ("There were 14 balloons, 5 popped. How many now?", 9),
            ("8 flowers bloomed, then 7 more bloomed. How many now?", 15),
            ("I had 12 stars, I lost 4. How many now?", 8),
            ("There were 9 apples, 6 more were picked. How many now?", 15),
            ("16 balloons, 7 popped. How many now?", 9),
            ("There were 11 flowers, 3 were picked. How many left?", 8),
            ("I had 13 stars, I got 2 more. How many now?", 15),
        ]
        for text, ans in riddles:
            items.append(q(text, "word", f"Answer = ____ (Answer: {ans})"))
        for i in range(19 - len(riddles)):
            items.append(_gen_riddle(8, 16, 2, 7, _kind(i), "more" if i % 2 == 0 else "less"))
        return items
    items = [cb("Number Riddles — No Pictures",
                 ["Solve using numbers only, just like a story problem."], "")]
    riddles = [
        ("A number is 1 more than 9. What is it?", 10),
        ("A number is 1 less than 15. What is it?", 14),
        ("Start at 12, count 3 more. Where do you land?", 15),
        ("Start at 18, count 4 less. Where do you land?", 14),
        ("A number is 1 more than 16. What is it?", 17),
        ("A number is 1 less than 20. What is it?", 19),
        ("Start at 5, count 6 more. Where do you land?", 11),
        ("Start at 19, count 5 less. Where do you land?", 14),
        ("A number is 1 more than 13. What is it?", 14),
    ]
    for text, ans in riddles:
        items.append(q(text, "fill", f"Answer = ____ (Answer: {ans})"))
    extra_templates = [
        ("A number is {c} more than {s}. What is it?", lambda s, c: s + c),
        ("A number is {c} less than {s}. What is it?", lambda s, c: s - c),
    ]
    random.seed(701)
    for i in range(19 - len(riddles)):
        s = random.randint(5, 19)
        c = random.randint(1, min(5, s - 1))
        tpl, fn = extra_templates[i % 2]
        items.append(q(tpl.format(s=s, c=c), "fill", f"Answer = ____ (Answer: {fn(s, c)})"))
    return items


# ───────────────────────── PreCUM3: all Pre-Level skills mixed ─────────────────────────

def _CUM3_s(sheet):
    random.seed(800 + sheet)
    if sheet == 1:
        items = [cb("Pre-Level Full Review — Concrete",
                     ["This sheet mixes counting, one more, one less and comparing."], "")]
        for i in range(5):
            items.append(_count_q(random.randint(1, 20), _kind(i)))
        for i in range(5):
            items.append(_one_more_q(random.randint(1, 14), _kind(i)))
        for i in range(5):
            items.append(_one_less_q(random.randint(2, 15), _kind(i)))
        for i in range(4):
            items.append(_compare_q(random.randint(1, 8), random.randint(1, 8), _kind(i)))
        return items
    if sheet == 2:
        items = [cb("Pre-Level Full Review — Pictorial",
                     ["Use rows of 5 to help with every question."], "")]
        for i in range(19):
            items.append(_count_q(random.randint(1, 20), _kind(i), group_size=5))
        return items
    if sheet == 3:
        items = [tb("Final Review Tips",
                     ["Read each question type carefully — counting, more, less, or compare.",
                      "Take your time — there is no rush."])]
        for n in [random.choice(range(1, 20)) for _ in range(19)]:
            items.append(q(f"What is one more than {n} and one less than {n}?",
                            "fill", "More = ____  Less = ____"))
        return items
    items = [cb("Pre-Level Full Review — Abstract",
                 ["No pictures this time — numbers only."], "")]
    for n in [random.choice(range(1, 20)) for _ in range(19)]:
        items.append(q(f"Write the number before and after {n}.", "fill", "Before = ____  After = ____"))
    return items


# ───────────────────────── PreREV: Full Pre-Level revision ─────────────────────────

def _REV_s(sheet):
    random.seed(900 + sheet)
    items = [cb("Pre-Level Revision — All Topics",
                 ["This sheet tests everything from the Pre-Level: counting 1-20, one more/less, comparing, and simple riddles.",
                  "Show your counting clearly."],
                 "Take it one question at a time")]
    if sheet in (1, 2):
        for i in range(13):
            items.append(_count_q(random.randint(1, 20), _kind(i), group_size=5 if sheet == 2 else 10))
        for i in range(4):
            items.append(_compare_q(random.randint(1, 8), random.randint(1, 8), _kind(i)))
        for i in range(2):
            items.append(_one_more_q(random.randint(1, 14), _kind(i)))
    elif sheet == 3:
        for n in [random.choice(range(1, 20)) for _ in range(16)]:
            items.append(q(f"What comes before and after {n}?", "fill", "Before=____ After=____"))
        items.append(q("I have 4 stars and get 3 more. How many now?", "word", "Answer = ____ (Answer: 7)"))
        items.append(q("I have 9 apples and eat 2. How many are left?", "word", "Answer = ____ (Answer: 7)"))
        items.append(q("There are 6 balloons and 4 more come. How many now?", "word", "Answer = ____ (Answer: 10)"))
    else:
        for n in [random.choice(range(1, 20)) for _ in range(19)]:
            items.append(q(f"Write the number that is one more than {n} and one less than {n}.",
                            "fill", "More=____ Less=____"))
    return items


# ───────────────────────── Dispatcher for Pre-Level ─────────────────────────

PRE_DISPATCH = {
    "A":    {1: lambda: _A_s(1), 2: lambda: _A_s(2), 3: lambda: _A_s(3), 4: lambda: _A_s(4)},
    "B":    {1: lambda: _B_s(1), 2: lambda: _B_s(2), 3: lambda: _B_s(3), 4: lambda: _B_s(4)},
    "C":    {1: lambda: _C_s(1), 2: lambda: _C_s(2), 3: lambda: _C_s(3), 4: lambda: _C_s(4)},
    "D":    {1: lambda: _D_s(1), 2: lambda: _D_s(2), 3: lambda: _D_s(3), 4: lambda: _D_s(4)},
    "CUM1": {1: lambda: _CUM1_s(1), 2: lambda: _CUM1_s(2), 3: lambda: _CUM1_s(3), 4: lambda: _CUM1_s(4)},
    "E":    {1: lambda: _E_s(1), 2: lambda: _E_s(2), 3: lambda: _E_s(3), 4: lambda: _E_s(4)},
    "F":    {1: lambda: _F_s(1), 2: lambda: _F_s(2), 3: lambda: _F_s(3), 4: lambda: _F_s(4)},
    "G":    {1: lambda: _G_s(1), 2: lambda: _G_s(2), 3: lambda: _G_s(3), 4: lambda: _G_s(4)},
    "CUM2": {1: lambda: _CUM2_s(1), 2: lambda: _CUM2_s(2), 3: lambda: _CUM2_s(3), 4: lambda: _CUM2_s(4)},
    "H":    {1: lambda: _H_s(1), 2: lambda: _H_s(2), 3: lambda: _H_s(3), 4: lambda: _H_s(4)},
    "I":    {1: lambda: _I_s(1), 2: lambda: _I_s(2), 3: lambda: _I_s(3), 4: lambda: _I_s(4)},
    "CUM3": {1: lambda: _CUM3_s(1), 2: lambda: _CUM3_s(2), 3: lambda: _CUM3_s(3), 4: lambda: _CUM3_s(4)},
    "REV":  {1: lambda: _REV_s(1), 2: lambda: _REV_s(2), 3: lambda: _REV_s(3), 4: lambda: _REV_s(4)},
}
