"""
Fear Less Maths — PRE-LEVEL Content (Pre-Primary / Class 1 entry)
Singapore-Math CPA approach: Concrete -> Pictorial -> Pictorial-Abstract bridge -> Abstract.
Every sub-level has exactly 4 sheets matching the existing Intro/Concept/Practice/Mastery
naming used everywhere else in the app, but the MEANING of each sheet is redefined here
to follow CPA stages (see table below). Remedial (R) variants are auto-generated by
remedialise() in content.py, extended to also shrink object counts in diagram params.

CPA <-> Sheet mapping used in every PreLevel sub-level:
  Sheet 1  Intro     = Concrete    : real objects, rows of <=5, plain counting
  Sheet 2  Concept   = Pictorial   : objects grouped in 5s/10s (subitizing) + concept box
  Sheet 3  Practice  = Bridge      : objects + number support (tips box, partial symbols)
  Sheet 4  Mastery   = Abstract    : numbers/symbols only, no images

Object kinds cycle through: apple, star, balloon, flower  (matches diagram_engine.py)
"""
import random
from content import cb, tb, q, remedialise, q_eq1, q_cmp, q_seq, q_cmp_big, q_place

OBJ_KINDS = ["apple", "star", "balloon", "flower"]


def _kind(i):
    return OBJ_KINDS[i % len(OBJ_KINDS)]


def _count_q(n, kind, group_size=5):
    """One counting question: image + short instruction + blank box."""
    return q("Count the objects.", "diagram", "____", "", "object_group",
              {"count": n, "kind": kind, "group_size": group_size})


def _compare_q(left, right, kind):
    """Comparison: two groups + >/</= tick-boxes baked into the image."""
    return q("Compare the groups.", "diagram", "____", "", "compare_choice",
              {"left_count": left, "right_count": right, "kind": kind})


def _draw_q(n):
    """Reverse-direction question: big numeral + empty box for the child to
    draw that many objects."""
    return q("Draw that many objects.", "diagram", "____", "", "number_card", {"n": n})


def _one_more_q(n, kind):
    """Visual '+1' equation: n objects + 1 object = blank box."""
    return q("Add one more.", "diagram", "____", "", "visual_equation",
              {"left": n, "right": 1, "kind": kind, "op": "+"})


def _one_less_q(n, kind):
    """Visual '-1' equation: n objects, second group taken away = blank box."""
    return q("Take one away.", "diagram", "____", "", "visual_equation",
              {"left": n, "right": 1, "kind": kind, "op": "-"})



def _gen_riddle(lo_start, hi_start, lo_change, hi_change, kind, op="more"):
    """Generates an addition/subtraction visual equation with a short
    instruction (objects + symbol + objects/crossed-out = blank box)."""
    start = random.randint(lo_start, hi_start)
    change = random.randint(lo_change, hi_change)
    if op == "more":
        return q("Add the numbers.", "diagram", "____", "", "visual_equation",
                  {"left": start, "right": change, "kind": kind, "op": "+"})
    else:
        change = min(change, start - 1) if start > 1 else 1
        return q("Subtract the numbers.", "diagram", "____", "", "visual_equation",
                  {"left": start, "right": change, "kind": kind, "op": "-"})


# ───────────────────────── Counting blocks: PreA-PreD (1-20) ─────────────────────────

def _counting_block(lo, hi, sheet, label):
    """Builds one sheet (Intro/Concept/Practice/Mastery) for a counting range lo..hi."""
    random.seed(lo * 10 + sheet)
    span = list(range(lo, hi + 1))
    picks = [random.choice(span) for _ in range(19)]  # sample w/ replacement, enough for ~16 real Qs

    if sheet == 1:  # Concrete — plain object counting, single kind per question
        items = [cb(f"Counting {lo} to {hi}",
                     ["Touch each object and count one by one.",
                      "Say the number out loud as you touch it.",
                      "Count slowly — do not skip any object."],
                     f"Count: {lo}, {lo+1}, {lo+2}... up to {hi}")]
        for idx, n in enumerate(picks):
            items.append(_count_q(n, _kind(idx)))
        return items

    if sheet == 2:  # Pictorial — grouped in 5s, subitizing
        items = [cb("Counting in Groups of 5",
                     ["Objects are arranged in rows of 5.",
                      "Count one full row first — that is 5.",
                      "Then count the extra objects in the next row."],
                     "Row of 5 + 2 more = 7")]
        for idx, n in enumerate(picks):
            items.append(_count_q(n, _kind(idx), group_size=5))
        return items

    if sheet == 3:  # Bridge — tips box, mix of counting + reverse drawing
        items = [tb(f"Tips for Counting {lo}-{hi}",
                     ["Always start counting from 1, not from the last object.",
                      "Move your finger under each object as you count.",
                      "Check your answer by counting again."])]
        for idx, n in enumerate(picks[:12]):
            items.append(_count_q(n, _kind(idx)))
        for n in picks[12:19]:
            items.append(_draw_q(n))
        return items

    # sheet == 4: Abstract — numbers/symbols only, zero words
    items = [cb(f"Numbers {lo} to {hi}",
                 ["We can also count using number words, without pictures.",
                  "Numbers go up by 1 each time.",
                  f"After {hi-1} comes {hi}."],
                 f"{hi-2}, {hi-1}, {hi}")]
    for n in picks[:10]:
        items.append(q_eq1(n, "+", _kind(n)))
    for n in picks[10:19]:
        items.append(q_eq1(n, "-", _kind(n)))
    return items


def _A_s(sheet): return _counting_block(1, 5, sheet, "A")
def _B_s(sheet): return _counting_block(6, 10, sheet, "B")
def _C_s(sheet): return _counting_block(11, 15, sheet, "C")
def _D_s(sheet): return _counting_block(16, 20, sheet, "D")


# ───────────────────────── PreCUM1: cumulative review 1-20 ─────────────────────────

def _CUM1_s(sheet):
    random.seed(100 + sheet)
    counts = [random.choice(range(1, 21)) for _ in range(19)]
    if sheet == 1:
        items = [cb("Review: Counting 1 to 20",
                     ["This sheet mixes numbers from 1 to 20.",
                      "Count carefully — some groups are small, some are bigger."],
                     "Practice counting any group from 1 to 20")]
        items += [_count_q(n, _kind(i)) for i, n in enumerate(counts)]
        return items
    if sheet == 2:
        items = [cb("Review: Counting in Groups",
                     ["Look for full rows of 5 first.",
                      "Then add the leftover objects."],
                     "5 + 5 + 3 = 13")]
        items += [_count_q(n, _kind(i), group_size=5) for i, n in enumerate(counts)]
        return items
    if sheet == 3:
        items = [tb("Review Tips",
                     ["If you lose count, start over from 1.",
                      "Counting out loud helps you stay accurate."])]
        items += [_count_q(n, _kind(i)) for i, n in enumerate(counts[:11])]
        items += [_draw_q(n) for n in counts[11:19]]
        return items
    items = [cb("Numbers 1 to 20 — No Pictures",
                 ["You should now recognise numbers without counting objects.",
                  "Practice writing numbers in order."],
                 "1, 2, 3 ... 20")]
    for n in counts:
        items.append(q_eq1(n, "+", _kind(n)))
    return items


# ───────────────────────── PreE: Number-to-picture matching (reverse) ─────────────────────────

def _E_s(sheet):
    random.seed(200 + sheet)
    if sheet == 1:
        items = [cb("From Number to Picture",
                     ["This time you see a NUMBER first.",
                      "Draw that many objects in the box.",
                      "Count your drawing to check it matches the number."],
                     "Number 4 -> draw 4 circles")]
        for n in [random.choice(range(1, 6)) for _ in range(19)]:
            items.append(_draw_q(n))
        return items
    if sheet == 2:
        items = [cb("Matching Groups of 5 and 10",
                     ["If the number is more than 5, draw one row of 5 first.",
                      "Then draw the rest in a second row."],
                     "Number 8 -> row of 5 + row of 3")]
        for n in [random.choice(range(6, 11)) for _ in range(19)]:
            items.append(_draw_q(n))
        return items
    if sheet == 3:
        items = [tb("Drawing Tips",
                     ["Draw simple shapes like circles or stars — keep them small.",
                      "Leave a little space between each object so counting is easy."])]
        for n in [random.choice(range(1, 16)) for _ in range(19)]:
            items.append(_draw_q(n))
        return items
    items = [cb("Number Recognition", ["Match numbers without drawing — just identify them."],
                "Which is bigger, 12 or 15? -> 15")]
    for _ in range(19):
        a, b = random.sample(range(1, 21), 2)
        items.append(q_cmp(a, b, _kind(a)))
    return items


# ───────────────────────── PreF: One More ─────────────────────────

def _F_s(sheet):
    random.seed(300 + sheet)
    nums = [random.choice(range(1, 15)) for _ in range(19)]
    if sheet == 1:
        items = [cb("One More",
                     ["When we add ONE MORE, we move forward by 1.",
                      "Count the objects, then add 1 more and count again."],
                     "3 apples + 1 more = 4 apples")]
        items += [_one_more_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 2:
        items = [cb("One More — Using Groups",
                     ["Count the full row of 5 first, then the extra ones.",
                      "Adding one more only changes the last group."],
                     "Row of 5 + 2, one more makes Row of 5 + 3")]
        items += [_one_more_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 3:
        items = [tb("One More Tips",
                     ["'One more' always means add 1.",
                      "The new number is always 1 bigger than before."])]
        for n in nums:
            items.append(q_eq1(n, "+", _kind(n)))
        return items
    items = [cb("One More — Numbers Only",
                 ["You no longer need pictures — just add 1 to the number."],
                 "One more than 9 is 10")]
    for n in [random.choice(range(1, 21)) for _ in range(19)]:
        items.append(q_eq1(n, "+", _kind(n)))
    return items


# ───────────────────────── PreG: One Less ─────────────────────────

def _G_s(sheet):
    random.seed(400 + sheet)
    nums = [random.choice(range(2, 16)) for _ in range(19)]
    if sheet == 1:
        items = [cb("One Less",
                     ["When we take away ONE, we move backward by 1.",
                      "Cross out one object, then count what is left."],
                     "5 stars, cross out 1 = 4 stars")]
        items += [_one_less_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 2:
        items = [cb("One Less — Using Groups",
                     ["If a full row of 5 has one removed, it becomes 4.",
                      "Count groups first, then subtract 1 from the total."],
                     "Row of 5, minus 1 = 4")]
        items += [_one_less_q(n, _kind(i)) for i, n in enumerate(nums)]
        return items
    if sheet == 3:
        items = [tb("One Less Tips",
                     ["'One less' always means subtract 1.",
                      "The new number is always 1 smaller than before."])]
        for n in nums:
            items.append(q_eq1(n, "-", _kind(n)))
        return items
    items = [cb("One Less — Numbers Only",
                 ["Subtract 1 from the number directly — no pictures needed."],
                 "One less than 10 is 9")]
    for n in [random.choice(range(2, 21)) for _ in range(19)]:
        items.append(q_eq1(n, "-", _kind(n)))
    return items


# ───────────────────────── PreCUM2: One more / one less combined ─────────────────────────

def _CUM2_s(sheet):
    random.seed(500 + sheet)
    nums = [random.choice(range(2, 19)) for _ in range(19)]
    if sheet == 1:
        items = [cb("Review: One More & One Less",
                     ["One more means +1. One less means -1.",
                      "Read each question carefully before answering."],
                     "One more than 6 = 7.  One less than 6 = 5.")]
        for i, n in enumerate(nums[:10]):
            items.append(_one_more_q(n, _kind(i)))
        for i, n in enumerate(nums[10:]):
            items.append(_one_less_q(n, _kind(i)))
        return items
    if sheet == 2:
        items = [cb("Review — Using Groups of 5", ["Use the rows of 5 to check your counting."],
                     "Group view helps avoid mistakes")]
        for i, n in enumerate(nums[:10]):
            items.append(_one_more_q(n, _kind(i)))
        for i, n in enumerate(nums[10:]):
            items.append(_one_less_q(n, _kind(i)))
        return items
    if sheet == 3:
        items = [tb("Review Tips", ["Look for the words 'more' or 'less' before answering.",
                                     "More = bigger number. Less = smaller number."])]
        for n in nums:
            items.append(q_seq([n-1, None, n+1], "pattern"))
        return items
    items = [cb("Numbers Only — One More / One Less",
                 ["Apply +1 or -1 directly to the number."], "")]
    for n in nums:
        items.append(q_seq([n-1, None, n+1], "pattern"))
    return items


# ───────────────────────── PreH: Comparing groups (more/fewer) ─────────────────────────

def _H_s(sheet):
    random.seed(600 + sheet)
    pairs = [(random.randint(1, 8), random.randint(1, 8)) for _ in range(19)]
    if sheet == 1:
        items = [cb("More or Fewer",
                     ["Look at two groups of objects.",
                      "The group with MORE objects has a bigger number.",
                      "Compare by counting each group separately."],
                     "4 apples vs 6 apples -> 6 is more")]
        items += [_compare_q(l, r, _kind(i)) for i, (l, r) in enumerate(pairs)]
        return items
    if sheet == 2:
        items = [cb("Comparing Using Groups of 5",
                     ["Line up both groups in rows of 5 to compare faster.",
                      "Whichever group fills more rows is bigger."],
                     "")]
        items += [_compare_q(l, r, _kind(i)) for i, (l, r) in enumerate(pairs)]
        return items
    if sheet == 3:
        items = [tb("Comparing Tips",
                     ["Count both groups fully before deciding.",
                      "Do not guess by size of the picture — always count."])]
        for l, r in pairs:
            items.append(q_cmp(l, r, _kind(l)))
        return items
    items = [cb("Comparing Numbers", ["Compare numbers directly without pictures."], "7 > 5")]
    for l, r in pairs:
        items.append(q_cmp(l, r, _kind(l)))
    return items


# ───────────────────────── PreI: Simple picture puzzles ─────────────────────────

def _I_s(sheet):
    random.seed(700 + sheet)
    if sheet == 1:
        items = [cb("", [], "",
                     icon_diagram="instruction_icon", icon_params={"symbols": ["+", "-"]})]
        fixed = [(2,2,"+","balloon"), (5,1,"-","star"), (3,2,"+","flower"), (4,1,"-","apple"),
                 (1,4,"+","balloon"), (2,2,"+","apple"), (4,1,"-","star"), (3,1,"+","balloon"),
                 (2,1,"-","flower"), (1,3,"+","apple"), (5,2,"-","star"), (1,1,"+","balloon")]
        for l, r, op, kind in fixed:
            txt = "Add the numbers." if op == "+" else "Subtract the numbers."
            items.append(q(txt, "diagram", "____", "", "visual_equation",
                            {"left": l, "right": r, "kind": kind, "op": op}))
        for i in range(19 - len(fixed)):
            items.append(_gen_riddle(1, 5, 1, 4, _kind(i), "more" if i % 2 == 0 else "less"))
        return items
    if sheet == 2:
        items = [cb("GROUP PUZZLES", ["ROWS OF 5 = FAST"], "")]
        fixed = [(6,3,"+","apple"), (8,2,"-","star"), (7,2,"-","balloon"), (5,5,"+","flower"),
                 (9,4,"-","apple"), (6,4,"+","star"), (10,3,"-","balloon"), (8,2,"+","flower"),
                 (7,5,"-","apple"), (6,6,"+","balloon"), (9,3,"-","star")]
        for l, r, op, kind in fixed:
            txt = "Add the numbers." if op == "+" else "Subtract the numbers."
            items.append(q(txt, "diagram", "____", "", "visual_equation",
                            {"left": l, "right": r, "kind": kind, "op": op}))
        for i in range(19 - len(fixed)):
            items.append(_gen_riddle(4, 9, 1, 5, _kind(i), "more" if i % 2 == 0 else "less"))
        return items
    if sheet == 3:
        items = [tb("PUZZLE TIPS", ["PLUS = TOGETHER", "MINUS = TAKE AWAY"])]
        fixed = [(10,3,"-","star"), (6,6,"+","apple"), (14,5,"-","balloon"), (8,7,"+","flower"),
                 (12,4,"-","star"), (9,6,"+","apple"), (16,7,"-","balloon"), (11,3,"-","flower"),
                 (13,2,"+","star")]
        for l, r, op, kind in fixed:
            txt = "Add the numbers." if op == "+" else "Subtract the numbers."
            items.append(q(txt, "diagram", "____", "", "visual_equation",
                            {"left": l, "right": r, "kind": kind, "op": op}))
        for i in range(19 - len(fixed)):
            items.append(_gen_riddle(8, 16, 2, 7, _kind(i), "more" if i % 2 == 0 else "less"))
        return items
    # sheet 4: abstract — pure symbolic equations, zero words
    items = [cb("NUMBER PUZZLES", ["JUST NUMBERS NOW"], "")]
    fixed = [(9,1,"+",10), (15,1,"-",14), (12,3,"+",15), (18,4,"-",14),
             (16,1,"+",17), (20,1,"-",19), (5,6,"+",11), (19,5,"-",14), (13,1,"+",14)]
    for s, c, op, ans in fixed:
        txt = "Add the numbers." if op == "+" else "Subtract the numbers."
        items.append(q(txt, "diagram", "____", "", "visual_equation", {"left": s, "right": c, "kind": _kind(s), "op": op}))
    random.seed(701)
    for i in range(19 - len(fixed)):
        s = random.randint(5, 19)
        c = random.randint(1, min(5, s - 1))
        op = "+" if i % 2 == 0 else "-"
        txt = "Add the numbers." if op == "+" else "Subtract the numbers."
        items.append(q(txt, "diagram", "____", "", "visual_equation", {"left": s, "right": c, "kind": _kind(s), "op": op}))
    return items


# ───────────────────────── PreCUM3: all Pre-Level skills mixed ─────────────────────────

def _CUM3_s(sheet):
    random.seed(800 + sheet)
    if sheet == 1:
        items = [cb("MIX-UP REVIEW",
                     ["MIX IT UP!"], "")]
        for i in range(5):
            items.append(_count_q(random.randint(1, 20), _kind(i)))
        for i in range(5):
            items.append(_one_more_q(random.randint(1, 14), _kind(i)))
        for i in range(5):
            items.append(_one_less_q(random.randint(2, 15), _kind(i)))
        for i in range(4):
            items.append(_compare_q(random.randint(1, 8), random.randint(1, 8), _kind(i)))
        return items
    if sheet == 2:
        items = [cb("REVIEW TIME", ["ROWS OF 5 = FAST"], "")]
        for i in range(19):
            items.append(_count_q(random.randint(1, 20), _kind(i), group_size=5))
        return items
    if sheet == 3:
        items = [tb("REVIEW TIPS", ["SLOW AND STEADY"])]
        for n in [random.choice(range(1, 20)) for _ in range(19)]:
            items.append(q_seq([n-1, None, n+1], "pattern"))
        return items
    items = [cb("NUMBERS ROUND", ["NO PICTURES NOW"], "")]
    for n in [random.choice(range(1, 20)) for _ in range(19)]:
        items.append(q_seq([n-1, None, n+1], "pattern"))
    return items


# ───────────────────────── PreREV: Full Pre-Level revision ─────────────────────────

def _REV_s(sheet):
    random.seed(900 + sheet)
    items = [cb("FINAL CHALLENGE!", ["YOU CAN DO IT!"], "")]
    if sheet in (1, 2):
        for i in range(13):
            items.append(_count_q(random.randint(1, 20), _kind(i), group_size=5 if sheet == 2 else 10))
        for i in range(4):
            items.append(_compare_q(random.randint(1, 8), random.randint(1, 8), _kind(i)))
        for i in range(2):
            items.append(_one_more_q(random.randint(1, 14), _kind(i)))
    elif sheet == 3:
        for n in [random.choice(range(1, 20)) for _ in range(16)]:
            items.append(q_seq([n-1, None, n+1], "pattern"))
        items.append(q("Add the numbers.", "diagram", "____", "", "visual_equation",
                        {"left": 4, "right": 3, "kind": "star", "op": "+"}))
        items.append(q("Subtract the numbers.", "diagram", "____", "", "visual_equation",
                        {"left": 9, "right": 2, "kind": "apple", "op": "-"}))
        items.append(q("Add the numbers.", "diagram", "____", "", "visual_equation",
                        {"left": 6, "right": 4, "kind": "balloon", "op": "+"}))
    else:
        for n in [random.choice(range(1, 20)) for _ in range(19)]:
            items.append(q_seq([n-1, None, n+1], "pattern"))
    return items


# ───────────────────────── Dispatcher for Pre-Level ─────────────────────────

PRE_DISPATCH = {
    "A":    {1: lambda: _A_s(1), 2: lambda: _A_s(2), 3: lambda: _A_s(3), 4: lambda: _A_s(4)},
    "B":    {1: lambda: _B_s(1), 2: lambda: _B_s(2), 3: lambda: _B_s(3), 4: lambda: _B_s(4)},
    "C":    {1: lambda: _C_s(1), 2: lambda: _C_s(2), 3: lambda: _C_s(3), 4: lambda: _C_s(4)},
    "D":    {1: lambda: _D_s(1), 2: lambda: _D_s(2), 3: lambda: _D_s(3), 4: lambda: _D_s(4)},
    "CUM1": {1: lambda: _CUM1_s(1), 2: lambda: _CUM1_s(2), 3: lambda: _CUM1_s(3), 4: lambda: _CUM1_s(4)},
    "E":    {1: lambda: _E_s(1), 2: lambda: _E_s(2), 3: lambda: _E_s(3), 4: lambda: _E_s(4)},
    "F":    {1: lambda: _F_s(1), 2: lambda: _F_s(2), 3: lambda: _F_s(3), 4: lambda: _F_s(4)},
    "G":    {1: lambda: _G_s(1), 2: lambda: _G_s(2), 3: lambda: _G_s(3), 4: lambda: _G_s(4)},
    "CUM2": {1: lambda: _CUM2_s(1), 2: lambda: _CUM2_s(2), 3: lambda: _CUM2_s(3), 4: lambda: _CUM2_s(4)},
    "H":    {1: lambda: _H_s(1), 2: lambda: _H_s(2), 3: lambda: _H_s(3), 4: lambda: _H_s(4)},
    "I":    {1: lambda: _I_s(1), 2: lambda: _I_s(2), 3: lambda: _I_s(3), 4: lambda: _I_s(4)},
    "CUM3": {1: lambda: _CUM3_s(1), 2: lambda: _CUM3_s(2), 3: lambda: _CUM3_s(3), 4: lambda: _CUM3_s(4)},
    "REV":  {1: lambda: _REV_s(1), 2: lambda: _REV_s(2), 3: lambda: _REV_s(3), 4: lambda: _REV_s(4)},
}
