"""Fear Less Maths — Level metadata (names, sublevel lists, tier names)."""

LEVELS = {
    0:  {"name": "Pre-Level — Counting & Number Sense (Pre-Primary)"},
    21: {"name": "Pre Level 1 — Counting & Numbers (Class 1-2, Small Steps)"},
    22: {"name": "Pre Level 2 — Even, Odd & Primes (Class 1-2, Small Steps)"},
    23: {"name": "Pre Level 3 — Addition & Subtraction (Class 1-2, Small Steps)"},
    24: {"name": "Pre Level 4 — Multiplication (Class 1-2, Small Steps)"},
    25: {"name": "Pre Level 5 — Division (Class 1-2, Small Steps)"},
    1:  {"name": "Counting & Numbers"},
    2:  {"name": "Even, Odd & Primes"},
    3:  {"name": "Addition & Subtraction"},
    4:  {"name": "Multiplication"},
    5:  {"name": "Division"},
    6:  {"name": "Fractions"},
    7:  {"name": "Decimals"},
    8:  {"name": "Integers"},
    9:  {"name": "Factors, Multiples & HCF/LCM"},
    10: {"name": "Ratio & Proportion"},
    11: {"name": "Algebra — Expressions"},
    12: {"name": "Algebra — Equations"},
    13: {"name": "Powers & Indices"},
    14: {"name": "Polynomials"},
    15: {"name": "Coordinate Geometry"},
    16: {"name": "Lines, Angles & Triangles"},
    17: {"name": "Quadrilaterals, Circles & Polygons"},
    18: {"name": "Mensuration"},
    19: {"name": "Trigonometry"},
    20: {"name": "Statistics, Probability & AP"},
}

SUBLEVELS = {
    0:  [("A","Counting 1-5 (objects)"),("B","Counting 6-10 (objects)"),
         ("C","Counting 11-15 (objects)"),("D","Counting 16-20 (objects)"),
         ("CUM1","Review: Counting 1-20"),
         ("E","Number-to-picture matching"),("F","One more"),("G","One less"),
         ("CUM2","Review: One more / One less"),
         ("H","Comparing groups (more/fewer)"),("I","Picture riddles"),
         ("CUM3","Mixed Pre-Level review"),("REV","Pre-Level Revision")],
    21: [("A","Counting 1–20 (review)"),("B","Counting 21–50"),("C","Counting 51–100"),
         ("CUM1","Review: Counting 1-100"),
         ("D","Number After (1-50)"),("E","Number Before (1-50)"),
         ("F","Before AND After (1-50)"),("G","Before/After (51-100)"),
         ("CUM2","Review: Before/After"),
         ("H","Greater/Smaller — objects (1-20)"),("I","Greater/Smaller — numbers (1-100)"),
         ("CUM3","Review: Greater/Smaller"),
         ("J","Missing numbers (1-50)"),("K","Missing numbers (51-100)"),
         ("CUM4","Review: Missing numbers"),
         ("L","Patterns — skip count by 2"),("M","Patterns — skip count by 5/10"),
         ("CUM5","Review: Patterns"),
         ("N","Place value — Tens & Ones (blocks)"),("O","Place value — Tens & Ones (numbers)"),
         ("CUM6","Review: Place value"),
         ("P","Counting objects & puzzles"),("Q","Mixed challenge"),
         ("REV","Level 21 Revision")],
    22: [("A","Pairing objects 1-10"),("B","Pairing objects 11-20"),
         ("CUM1","Review: Pairing/Even/Odd"),
         ("C","Even/Odd patterns (skip count by 2)"),("D","Even/Odd — bigger numbers"),
         ("CUM2","Review: Even/Odd"),
         ("E","Equal grouping (factors intro)"),
         ("F","Prime numbers"),("G","Composite numbers"),
         ("CUM3","Review: Prime/Composite"),
         ("H","Prime factor practice"),
         ("I","Picture puzzles"),("J","Mixed challenge"),
         ("REV","Level 22 Revision")],
    23: [("A","Addition - single digit"),("B","Addition - two digit (no carry)"),
         ("CUM1","Review: Addition"),
         ("C","Subtraction - single digit"),("D","Subtraction - two digit (no borrow)"),
         ("CUM2","Review: Subtraction"),
         ("E","Addition with carrying"),("F","Subtraction with borrowing"),
         ("CUM3","Review: Carrying/Borrowing"),
         ("G","Speed addition"),("H","Speed subtraction"),
         ("I","Picture puzzles"),("J","Mixed challenge"),
         ("REV","Level 23 Revision")],
    24: [("A","Multiplication concept"),("B","Tables 2-5"),("C","Tables 6-10"),
         ("CUM1","Review: Tables"),
         ("D","Multiplication practice"),("E","Multi-digit multiplication"),
         ("F","Picture word problems"),
         ("CUM2","Review: Practice/Multi-digit/Word problems"),
         ("G","Multiplication patterns"),("H","Speed multiplication"),
         ("I","Picture puzzles"),
         ("CUM3","Review: Patterns/Speed/Puzzles"),
         ("J","Mixed challenge"),("REV","Level 24 Revision")],
    25: [("A","Equal Grouping (how many groups?)"),("B","Equal Sharing (how many each?)"),
         ("CUM1","Review: Grouping vs Sharing"),
         ("C","Remainder - Grouping"),("D","Remainder - Sharing"),
         ("CUM2","Review: Remainders"),
         ("E","Bar Model division"),("F","Multiplication & Division fact families"),
         ("CUM3","Review: Bar Models & Fact Families"),
         ("G","Real-life word problems"),("H","Speed division"),
         ("I","Picture puzzles"),
         ("J","Mixed challenge"),("REV","Level 25 Revision")],
    1:  [("1A","Counting 1–50"),("1B","Counting 1–100"),("1C","Before / After numbers"),
         ("1CUM1","Mixed A+B+C"),("1D","Greater / Smaller"),("1E","Missing numbers"),
         ("1F","Number patterns"),("1CUM2","Mixed D+E+F"),("1G","Counting objects"),
         ("1H","Mixed numbers"),("1I","Puzzle numbers"),("1CUM3","Mixed G+H+I"),
         ("1J","Mixed challenge"),("1REV","Level 1 Revision")],
    2:  [("2A","Even numbers"),("2B","Odd numbers"),("2C","Even/Odd identification"),
         ("2CUM1","Mixed A+B+C"),("2D","Even/Odd patterns"),("2E","Prime numbers"),
         ("2F","Composite numbers"),("2CUM2","Mixed D+E+F"),("2G","Prime identification"),
         ("2H","Prime factor ideas"),("2I","Mixed classification"),("2CUM3","Mixed G+H+I"),
         ("2J","Puzzle numbers"),("2REV","Level 2 Revision")],
    3:  [("3A","Addition - single digit"),("3B","Addition - 2digit+1digit, no carry"),
         ("3C","Addition - 2digit+2digit, no carry"),
         ("3CUM1","Review: A/B/C"),
         ("3D","Carrying - concrete (trade action)"),("3E","Carrying - algorithm practice"),
         ("3CUM2","Review: D/E"),
         ("3F","Subtraction - single digit"),("3G","Subtraction - 2digit, no borrow"),
         ("3CUM3","Review: F/G"),
         ("3H","Borrowing - concrete (trade action)"),("3I","Borrowing - expanded form"),
         ("3J","Borrowing - algorithm practice"),
         ("3CUM4","Review: H/I/J"),
         ("3K","Addition+Subtraction mixed"),("3L","Word problems"),
         ("3CUM5","Review: K/L"),
         ("3M","Bond-to-10 & Doubles"),("3N","Compensation strategy"),
         ("3CUM6","Review: M/N"),
         ("3O","Puzzles - Tier 1"),("3P","Puzzles - Tier 2 (harder)"),
         ("3Q","Speed round"),("3R","Mixed challenge"),("3REV","Level 3 Revision")],
    4:  [("4A","Concept (repeated addition + arrays)"),
         ("4B","x0 and x1"),("4C","x2 and x10"),("4D","x5 (half of x10)"),
         ("4CUM1","Review: x0/x1/x2/x10/x5"),
         ("4E","x3 and x4 (4=double 2)"),("4F","x6 and x9 (9=x10 minus one group)"),
         ("4CUM2","Review: x3/x4/x6/x9"),
         ("4G","x8 (double the 4s)"),("4H","x7 (hardest, derived facts)"),
         ("4CUM3","Review: x7/x8"),
         ("4I","Square numbers"),("4J","Multi-digit (split method)"),
         ("4CUM4","Review: squares/split method"),
         ("4K","Word problems - one step"),("4L","Word problems - two step"),
         ("4CUM5","Review: word problems"),
         ("4M","Patterns"),("4N","Speed drills"),
         ("4CUM6","Review: patterns/speed"),
         ("4O","Puzzles - Tier 1"),("4P","Puzzles - Tier 2 (LCM/factors)"),
         ("4CUM7","Review: puzzles"),
         ("4Q","Mixed challenge"),("4REV","Level 4 Revision")],
    5:  [("5A","Concept (sharing/grouping)"),
         ("5B","Easy divisors: /2 /5 /10"),("5C","Mid divisors: /3 /4 /6 /9"),
         ("5D","Hard divisors: /7 /8"),
         ("5CUM1","Review: A-D"),
         ("5E","Remainders - concept"),("5F","Remainders - the CHECK step"),
         ("5CUM2","Review: E/F"),
         ("5G","Long division - area model bridge"),("5H","Long division - partial quotients"),
         ("5I","Long division - practice"),
         ("5CUM3","Review: G/H/I"),
         ("5J","Word problems - no remainder"),("5K","Word problems - with remainder"),
         ("5CUM4","Review: J/K"),
         ("5L","Fact families"),("5M","Missing numbers"),
         ("5CUM5","Review: L/M"),
         ("5N","Speed - basic facts"),("5O","Speed - /10 /100"),
         ("5CUM6","Review: N/O"),
         ("5P","Puzzles - Tier 1"),("5Q","Puzzles - Tier 2 (LCM/digits)"),
         ("5CUM7","Review: P/Q"),
         ("5R","Mixed challenge"),("5REV","Level 5 Revision")],
    6:  [("6A","Fraction concept + unit fractions"),("6B","Proper/improper/mixed"),("6C","Equivalent fractions"),
         ("6CUM1","Review: A/B/C"),
         ("6D","Simplify via GCF"),("6E","Compare fractions (LCM, benchmark, cross-multiplication)"),("6F","Add & subtract fractions"),
         ("6CUM2","Review: D/E/F"),
         ("6G","Add & subtract mixed numbers"),("6H","Multiply fractions & mixed numbers"),("6I","Divide fractions"),
         ("6CUM3","Review: G/H/I"),
         ("6J","Word problems & estimation"),("6REV","Level 6 Revision")],
    7:  [("7A","Tenths & hundredths"),("7B","Thousandths, place value & trailing zeros"),("7C","Comparing decimals"),
         ("7CUM1","Review: A/B/C"),
         ("7D","Spot the Mistake"),("7E","Decimal <-> Fraction"),("7F","Decimals on a number line"),
         ("7CUM2","Review: D/E/F"),
         ("7G","Add & subtract decimals"),("7H","Multiply decimals"),("7I","Divide decimals"),
         ("7CUM3","Review: G/H/I"),
         ("7J","Money, measurement & rounding"),("7REV","Level 7 Revision")],
    8:  [("8A","Integer concept & number line"),("8B","Integer addition & subtraction"),("8C","Properties of addition/subtraction"),
         ("8D","Integer multiplication & division"),("8E","Properties of multiplication/division"),("8F","Word problems + BODMAS"),
         ("8G","Integers mastery challenge"),("8H","Percentage concept"),("8I","Percentage of a quantity"),
         ("8J","Percentage increase & decrease"),("8K","Discount & profit/loss"),("8L","Simple interest & tax"),
         ("8M","Multi-step percentage word problems"),("8N","Level 8 mastery challenge & revision")],
    9:  [("9A","Factors"),("9B","Multiples"),("9C","Prime factorisation"),
         ("9CUM1","Factor trees"),("9D","HCF"),("9E","LCM"),
         ("9F","Word problems"),("9CUM2","HCF/LCM via Venn diagrams"),("9G","Applications"),
         ("9H","Euclidean Algorithm for HCF"),("9I","Puzzle"),("9CUM3","Prime number enrichment"),
         ("9J","Mastery challenge"),("9REV","Level 9 Revision")],
    10: [("10A","Ratio concept"),("10B","Simplifying ratios"),("10C","Equivalent ratios"),
         ("10CUM1","Ratio bar models"),("10D","Proportion"),("10E","Solving proportions"),
         ("10F","Word problems"),("10CUM2","Continued proportion & rates"),("10G","Direct proportion"),
         ("10H","Inverse proportion"),("10I","Direct/inverse proportion graphs"),("10CUM3","Compound proportion & partnership"),
         ("10J","Scale drawings & similar figures"),("10REV","Level 10 Revision")],
    11: [("11A","Variables"),("11B","Algebraic expressions"),("11C","Simplifying expressions"),
         ("11CUM1","Term structure & repeated addition"),("11D","Like / unlike terms"),("11E","Substitution"),
         ("11F","Expression evaluation"),("11CUM2","Function machines & substitution steps"),("11G","Word problems"),
         ("11H","Algebra tiles: collecting like terms"),("11I","Puzzle algebra"),("11CUM3","Distributive property & exponents"),
         ("11J","Equation balance challenge"),("11REV","Level 11 Revision")],
    12: [("12A","Equation concept"),("12B","Solving equations"),("12C","Multi-step equations"),
         ("12CUM1","Graphing linear equations"),("12D","Word problems"),("12E","Equation applications"),
         ("12F","Equation puzzles"),("12CUM2","Two-variable equations & substitution method"),("12G","Pair of equations: graphical & elimination methods"),
         ("12H","Speed solving"),("12I","Hard problems"),("12CUM3","Consistent, inconsistent & dependent systems"),
         ("12J","Cross-multiplication method challenge"),("12REV","Level 12 Revision")],
    13: [("13A","Powers concept"),("13B","Laws of indices"),("13C","Simplification"),
         ("13CUM1","Index law verification"),("13D","Negative powers"),("13E","Fractional powers"),
         ("13F","Scientific notation"),("13CUM2","Surds"),("13G","Word problems"),
         ("13H","Powers of ten scale"),("13I","Puzzle problems"),("13CUM3","Exponential growth vs decay"),
         ("13J","Powers mastery challenge"),("13REV","Level 13 Revision")],
    14: [("14A","Polynomial basics"),("14B","Addition"),("14C","Subtraction"),
         ("14CUM1","Area model for multiplication"),("14D","Multiplication"),("14E","Identities"),
         ("14F","Factorisation"),("14CUM2","Cube identities"),("14G","Polynomial problems"),
         ("14H","Geometrical meaning of zeroes"),("14I","Puzzle algebra"),("14CUM3","Long division & candidate zeroes"),
         ("14J","Polynomial mastery challenge"),("14REV","Level 14 Revision")],
    15: [("15A","Coordinate plane"),("15B","Plotting points"),("15C","Distance formula"),
         ("15CUM1","Plane, plotting & distance — visual practice"),("15D","Midpoint formula"),("15E","Section concept"),
         ("15F","Graph basics"),("15CUM2","Midpoint, section & graphing — visual practice"),("15G","Graph applications"),
         ("15H","Area of a triangle"),("15I","Puzzle graphs"),("15CUM3","Collinearity — the area test"),
         ("15J","Coordinate geometry mastery challenge"),("15REV","Level 15 Revision")],
    16: [("16A","Point, line, ray & angles"),("16B","Angle pair properties"),("16C","Parallel lines & transversal"),
         ("16CUM1","Types of triangles, angle sum & exterior angle"),("16D","Congruence of triangles"),("16E","Triangle inequality & isosceles theorem"),
         ("16F","Similar triangles"),("16CUM2","Basic proportionality & midpoint theorem"),("16G","Pythagoras theorem & converse"),
         ("16H","Applications"),("16I","Puzzle geometry"),("16CUM3","Areas on the same base"),
         ("16J","Mastery challenge"),("16REV","Level 16 Revision")],
    17: [("17A","Quadrilaterals: types & properties"),("17B","Quadrilaterals: angle sum & diagonals"),("17C","Circle basics & radius/diameter"),
         ("17CUM1","Chords"),("17D","Tangents"),("17E","Circle theorems"),
         ("17F","Cyclic quadrilaterals"),("17CUM2","Angle in a circle"),("17G","Applications"),
         ("17H","Polygons: interior angle sum"),("17I","Puzzle problems"),("17CUM3","Polygons: exterior angles & regular polygons"),
         ("17J","Mastery challenge"),("17REV","Level 17 Revision")],
    18: [("18A","Perimeter"),("18B","Area rectangle & square"),("18C","Area of triangle"),
         ("18CUM1","Mixed A+B+C"),("18D","Area of circle"),("18E","Surface area cube/cuboid"),
         ("18F","Cylinder & cone"),("18CUM2","Mixed D+E+F"),("18G","Sphere / hemisphere"),
         ("18H","Volume problems"),("18I","Mixed mensuration"),("18CUM3","Mixed G+H+I"),
         ("18J","Mixed challenge"),("18REV","Level 18 Revision")],
    19: [("19A","Trig ratios"),("19B","Trig table"),("19C","Basic simplification"),
         ("19CUM1","Mixed A+B+C"),("19D","Trig identities"),("19E","Heights & distances"),
         ("19F","Applications"),("19CUM2","Mixed D+E+F"),("19G","Mixed problems"),
         ("19H","Advanced simplification"),("19I","Puzzle trig"),("19CUM3","Mixed G+H+I"),
         ("19J","Mixed challenge"),("19REV","Level 19 Revision")],
    20: [("20A","AP basics"),("20B","AP problems"),("20C","AP word problems"),
         ("20CUM1","Mixed A+B+C"),("20D","Mean"),("20E","Median"),
         ("20F","Mode"),("20CUM2","Mixed D+E+F"),("20G","Probability basics"),
         ("20H","Probability problems"),("20I","Mixed statistics & probability"),("20CUM3","Mixed G+H+I"),
         ("20J","Grand challenge"),("20REV","Level 20 Revision")],
}

SHEET_OPTIONS = [
    ("1",  "Sheet 1 — See it (Intuition)"),
    ("2",  "Sheet 2 — Try it (Concept)"),
    ("3",  "Sheet 3 — Do it (Practice)"),
    ("3B", "Sheet 3B — Bridge it (Bridge)"),
    ("4",  "Sheet 4 — Master it (Mastery)"),
    ("1R", "Sheet 1R — Remedial"),
    ("2R", "Sheet 2R — Remedial"),
    ("3R", "Sheet 3R — Remedial"),
    ("3BR","Sheet 3BR — Bridge Remedial"),
    ("4R", "Sheet 4R — Remedial"),
]

def get_tier(sheet_num: str) -> str:
    base = sheet_num[:-1] if sheet_num.endswith("R") else sheet_num
    names = {"1":"Intuition","2":"Concept","3":"Practice","3B":"Bridge","4":"Mastery"}
    t = names.get(base,"Practice")
    return t + " (Remedial)" if sheet_num.endswith("R") else t
