"""Fear Less Maths — Level metadata (names, sublevel lists, tier names)."""

LEVELS = {
    0:  {"name": "Pre-Level — Counting & Number Sense (Pre-Primary)"},
    1:  {"name": "Counting & Numbers"},
    2:  {"name": "Even, Odd & Primes"},
    3:  {"name": "Addition & Subtraction"},
    4:  {"name": "Multiplication"},
    5:  {"name": "Division"},
    6:  {"name": "Fractions"},
    7:  {"name": "Decimals"},
    8:  {"name": "Integers"},
    9:  {"name": "Factors, Multiples & HCF/LCM"},
    10: {"name": "Ratio & Proportion"},
    11: {"name": "Algebra — Expressions"},
    12: {"name": "Algebra — Equations"},
    13: {"name": "Powers & Indices"},
    14: {"name": "Polynomials"},
    15: {"name": "Coordinate Geometry"},
    16: {"name": "Triangles"},
    17: {"name": "Circles"},
    18: {"name": "Mensuration"},
    19: {"name": "Trigonometry"},
    20: {"name": "Statistics, Probability & AP"},
}

SUBLEVELS = {
    0:  [("A","Counting 1-5 (objects)"),("B","Counting 6-10 (objects)"),
         ("C","Counting 11-15 (objects)"),("D","Counting 16-20 (objects)"),
         ("CUM1","Review: Counting 1-20"),
         ("E","Number-to-picture matching"),("F","One more"),("G","One less"),
         ("CUM2","Review: One more / One less"),
         ("H","Comparing groups (more/fewer)"),("I","Picture riddles"),
         ("CUM3","Mixed Pre-Level review"),("REV","Pre-Level Revision")],
    1:  [("1A","Counting 1–50"),("1B","Counting 1–100"),("1C","Before / After numbers"),
         ("1CUM1","Mixed A+B+C"),("1D","Greater / Smaller"),("1E","Missing numbers"),
         ("1F","Number patterns"),("1CUM2","Mixed D+E+F"),("1G","Counting objects"),
         ("1H","Mixed numbers"),("1I","Puzzle numbers"),("1CUM3","Mixed G+H+I"),
         ("1J","Mixed challenge"),("1REV","Level 1 Revision")],
    2:  [("2A","Even numbers"),("2B","Odd numbers"),("2C","Even/Odd identification"),
         ("2CUM1","Mixed A+B+C"),("2D","Even/Odd patterns"),("2E","Prime numbers"),
         ("2F","Composite numbers"),("2CUM2","Mixed D+E+F"),("2G","Prime identification"),
         ("2H","Prime factor ideas"),("2I","Mixed classification"),("2CUM3","Mixed G+H+I"),
         ("2J","Puzzle numbers"),("2REV","Level 2 Revision")],
    3:  [("3A","Addition single digit"),("3B","Addition two digit"),("3C","Subtraction basics"),
         ("3CUM1","Mixed A+B+C"),("3D","Borrow subtraction"),("3E","Addition + subtraction"),
         ("3F","Word problems"),("3CUM2","Mixed D+E+F"),("3G","Speed addition"),
         ("3H","Speed subtraction"),("3I","Puzzle operations"),("3CUM3","Mixed G+H+I"),
         ("3J","Mixed challenge"),("3REV","Level 3 Revision")],
    4:  [("4A","Multiplication concept"),("4B","Tables 2–5"),("4C","Tables 6–10"),
         ("4CUM1","Mixed A+B+C"),("4D","Multiplication practice"),("4E","Multi-digit multiplication"),
         ("4F","Word problems"),("4CUM2","Mixed D+E+F"),("4G","Multiplication patterns"),
         ("4H","Speed multiplication"),("4I","Puzzle multiplication"),("4CUM3","Mixed G+H+I"),
         ("4J","Mixed challenge"),("4REV","Level 4 Revision")],
    5:  [("5A","Division concept"),("5B","Division single digit"),("5C","Division remainder"),
         ("5CUM1","Mixed A+B+C"),("5D","Long division"),("5E","Word problems"),
         ("5F","Multiplication / division"),("5CUM2","Mixed D+E+F"),("5G","Missing numbers"),
         ("5H","Speed division"),("5I","Puzzle division"),("5CUM3","Mixed G+H+I"),
         ("5J","Mixed challenge"),("5REV","Level 5 Revision")],
    6:  [("6A","Fraction concept"),("6B","Proper / improper fractions"),("6C","Equivalent fractions"),
         ("6CUM1","Mixed A+B+C"),("6D","Fraction comparison"),("6E","Fraction addition"),
         ("6F","Fraction subtraction"),("6CUM2","Mixed D+E+F"),("6G","Word problems"),
         ("6H","Mixed fractions"),("6I","Puzzle fractions"),("6CUM3","Mixed G+H+I"),
         ("6J","Mixed challenge"),("6REV","Level 6 Revision")],
    7:  [("7A","Decimal concept"),("7B","Decimal place value"),("7C","Decimal comparison"),
         ("7CUM1","Mixed A+B+C"),("7D","Decimal addition"),("7E","Decimal subtraction"),
         ("7F","Fraction to decimal"),("7CUM2","Mixed D+E+F"),("7G","Word problems"),
         ("7H","Mixed decimals"),("7I","Decimal puzzles"),("7CUM3","Mixed G+H+I"),
         ("7J","Mixed challenge"),("7REV","Level 7 Revision")],
    8:  [("8A","Integer concept"),("8B","Number line"),("8C","Integer addition"),
         ("8CUM1","Mixed A+B+C"),("8D","Integer subtraction"),("8E","Integer multiplication"),
         ("8F","Integer division"),("8CUM2","Mixed D+E+F"),("8G","Word problems"),
         ("8H","Mixed integers"),("8I","Integer puzzles"),("8CUM3","Mixed G+H+I"),
         ("8J","Mixed challenge"),("8REV","Level 8 Revision")],
    9:  [("9A","Factors"),("9B","Multiples"),("9C","Prime factorisation"),
         ("9CUM1","Mixed A+B+C"),("9D","HCF"),("9E","LCM"),
         ("9F","Word problems"),("9CUM2","Mixed D+E+F"),("9G","Applications"),
         ("9H","Mixed"),("9I","Puzzle"),("9CUM3","Mixed G+H+I"),
         ("9J","Mixed challenge"),("9REV","Level 9 Revision")],
    10: [("10A","Ratio concept"),("10B","Simplifying ratios"),("10C","Equivalent ratios"),
         ("10CUM1","Mixed A+B+C"),("10D","Proportion"),("10E","Solving proportions"),
         ("10F","Word problems"),("10CUM2","Mixed D+E+F"),("10G","Direct proportion"),
         ("10H","Inverse proportion"),("10I","Mixed"),("10CUM3","Mixed G+H+I"),
         ("10J","Mixed challenge"),("10REV","Level 10 Revision")],
    11: [("11A","Variables"),("11B","Algebraic expressions"),("11C","Simplifying expressions"),
         ("11CUM1","Mixed A+B+C"),("11D","Like / unlike terms"),("11E","Substitution"),
         ("11F","Expression evaluation"),("11CUM2","Mixed D+E+F"),("11G","Word problems"),
         ("11H","Mixed expressions"),("11I","Puzzle algebra"),("11CUM3","Mixed G+H+I"),
         ("11J","Mixed challenge"),("11REV","Level 11 Revision")],
    12: [("12A","Equation concept"),("12B","Solving equations"),("12C","Multi-step equations"),
         ("12CUM1","Mixed A+B+C"),("12D","Word problems"),("12E","Equation applications"),
         ("12F","Equation puzzles"),("12CUM2","Mixed D+E+F"),("12G","Mixed equations"),
         ("12H","Speed solving"),("12I","Hard problems"),("12CUM3","Mixed G+H+I"),
         ("12J","Mixed challenge"),("12REV","Level 12 Revision")],
    13: [("13A","Powers concept"),("13B","Laws of indices"),("13C","Simplification"),
         ("13CUM1","Mixed A+B+C"),("13D","Negative powers"),("13E","Fractional powers"),
         ("13F","Scientific notation"),("13CUM2","Mixed D+E+F"),("13G","Word problems"),
         ("13H","Mixed"),("13I","Puzzle problems"),("13CUM3","Mixed G+H+I"),
         ("13J","Mixed challenge"),("13REV","Level 13 Revision")],
    14: [("14A","Polynomial basics"),("14B","Addition"),("14C","Subtraction"),
         ("14CUM1","Mixed A+B+C"),("14D","Multiplication"),("14E","Identities"),
         ("14F","Factorisation"),("14CUM2","Mixed D+E+F"),("14G","Polynomial problems"),
         ("14H","Mixed"),("14I","Puzzle algebra"),("14CUM3","Mixed G+H+I"),
         ("14J","Mixed challenge"),("14REV","Level 14 Revision")],
    15: [("15A","Coordinate plane"),("15B","Plotting points"),("15C","Distance formula"),
         ("15CUM1","Mixed A+B+C"),("15D","Midpoint formula"),("15E","Section concept"),
         ("15F","Graph basics"),("15CUM2","Mixed D+E+F"),("15G","Graph applications"),
         ("15H","Mixed"),("15I","Puzzle graphs"),("15CUM3","Mixed G+H+I"),
         ("15J","Mixed challenge"),("15REV","Level 15 Revision")],
    16: [("16A","Types of triangles"),("16B","Angle sum property"),("16C","Exterior angle theorem"),
         ("16CUM1","Mixed A+B+C"),("16D","Congruence"),("16E","Similar triangles"),
         ("16F","Pythagoras theorem"),("16CUM2","Mixed D+E+F"),("16G","Applications"),
         ("16H","Mixed"),("16I","Puzzle geometry"),("16CUM3","Mixed G+H+I"),
         ("16J","Mixed challenge"),("16REV","Level 16 Revision")],
    17: [("17A","Circle basics"),("17B","Radius / diameter"),("17C","Chords"),
         ("17CUM1","Mixed A+B+C"),("17D","Tangents"),("17E","Circle theorems"),
         ("17F","Angle in circle"),("17CUM2","Mixed D+E+F"),("17G","Applications"),
         ("17H","Mixed"),("17I","Puzzle problems"),("17CUM3","Mixed G+H+I"),
         ("17J","Mixed challenge"),("17REV","Level 17 Revision")],
    18: [("18A","Perimeter"),("18B","Area rectangle & square"),("18C","Area of triangle"),
         ("18CUM1","Mixed A+B+C"),("18D","Area of circle"),("18E","Surface area cube/cuboid"),
         ("18F","Cylinder & cone"),("18CUM2","Mixed D+E+F"),("18G","Sphere / hemisphere"),
         ("18H","Volume problems"),("18I","Mixed mensuration"),("18CUM3","Mixed G+H+I"),
         ("18J","Mixed challenge"),("18REV","Level 18 Revision")],
    19: [("19A","Trig ratios"),("19B","Trig table"),("19C","Basic simplification"),
         ("19CUM1","Mixed A+B+C"),("19D","Trig identities"),("19E","Heights & distances"),
         ("19F","Applications"),("19CUM2","Mixed D+E+F"),("19G","Mixed problems"),
         ("19H","Advanced simplification"),("19I","Puzzle trig"),("19CUM3","Mixed G+H+I"),
         ("19J","Mixed challenge"),("19REV","Level 19 Revision")],
    20: [("20A","AP basics"),("20B","AP problems"),("20C","AP word problems"),
         ("20CUM1","Mixed A+B+C"),("20D","Mean"),("20E","Median"),
         ("20F","Mode"),("20CUM2","Mixed D+E+F"),("20G","Probability basics"),
         ("20H","Probability problems"),("20I","Mixed statistics & probability"),("20CUM3","Mixed G+H+I"),
         ("20J","Grand challenge"),("20REV","Level 20 Revision")],
}

SHEET_OPTIONS = [
    ("1",  "Sheet 1 — See it (Intuition)"),
    ("2",  "Sheet 2 — Try it (Concept)"),
    ("3",  "Sheet 3 — Do it (Practice)"),
    ("4",  "Sheet 4 — Master it (Mastery)"),
    ("1R", "Sheet 1R — Remedial"),
    ("2R", "Sheet 2R — Remedial"),
    ("3R", "Sheet 3R — Remedial"),
    ("4R", "Sheet 4R — Remedial"),
]

def get_tier(sheet_num: str) -> str:
    base = sheet_num.replace("R","")
    names = {"1":"Intuition","2":"Concept","3":"Practice","4":"Mastery"}
    t = names.get(base,"Practice")
    return t + " (Remedial)" if sheet_num.endswith("R") else t
